### ISSUE TITLE
Add WF_APPICON to header file

### ISSUE THREAD

**Issue by xdelatour** [mikrosk/lib#21]
This patch adds WF_APPICON (201) to mt_gem.h.in.

By the way, there are a lot of questions:
- How to remove the icon? wind_set_str(wh, WF_APPICON, NULL)?
- What is the icon format ? In Xapp.rsc, it's a 16x15 CICON with one plane only
- Is wind_get_ptr(wh,WF_APPICON, ciconblkptr) working to get the pointer?
- appl_getinfo(AES_WINDOW) returns the availabiliy of WF_WIDGETS (200) in ap_gout2 (bit 0). Perhaps bit 1 is WF_APPICON?

[wf_appicon.patch.txt](https://github.com/freemint/gemlib/files/10965315/wf_appicon.patch.txt)

**Comment by th-otto** [comment]
Thanks for the patch.

As to the questions: the format should be clear (at least by looking at the sources of Xserver): it is a CICONBLK structure. So yes, that could also mean it is just a monochrome icon (if mainlist is empty, or there is only a 1-depth icon in it).

I don't think that wind_get() must be supported, since i think it is mainly intended for the application to allow to change the icon.

The bit for appl_getinfo() would make sense, but only a look in the developer documentation of N.AES 3.0 could tell whether that is actually the case.

Another question would be whether the AES is required to copy the data, or the application is responsible that the data remains valid as long as the window is not deleted.

Of course, all of this is rather hypothetical, as long as there is no AES supporting that mode.

I also wonder how this would interact with other programs like winframe, that implement a custom window frame manager, and among others also allow to change the icon on a per-application basis.

But generally, i find this is a useful feature.

**Comment by mikrosk** [comment]
Commited as https://github.com/freemint/gemlib/commit/b951fb98b3303914d94e96d25a01d807df0704f3, so closing. @xdelatour if you have more questions, feel free to post them here or in the mailing list.

**Comment by xdelatour** [comment]
I might have questions later:
- XaAES is almost ready for appicon (functions related to the WAPPICN widget are copy/paste of CLOSER widget and the WIDG_LOGO object is available in all resource files)
- there is no API available. The corresponding bit is in the most significant word of wkind (intin[5]). This is incompatible with Geneva's x_wind_create which uses intin[1]
- There is no function to modify the obspec, so there can't be compatibility with N.AES and subfunction 201 at the moment
- xa_defs.h contains the DISPLAY_LOGO_IN_TITLE constant which is not used anywhere. Btw this is a compile-time option only
